[tool.poetry]
name = "detectionmetrics-sphereformer"
version = "0.0.0"
description = "SphereFormer-compatible version of DetectionMetrics"
authors = ["JdeRobot", "d.pascualhe <d.pascualhe@gmail.com>"]
readme = "README.md"
license = "LICENSE"
packages = [
    { include = "detectionmetrics" }
]

[tool.poetry.dependencies]
python = "^3.7"
tqdm = "^4.65.0"
pandas = "^1.3.5"
PyYAML = "^5.4.1"
pyarrow = "^12.0.1"
pillow = "9.5.0"
numpy = "1.21.6"
opencv-python-headless = "^4.5.5.64"
scikit-learn = "^1.0.2"
open3d = "^0.13.0"
addict = "^2.4.0"
matplotlib = "^3.5.0"
click = "^8.0.4"
tensorboard = "^2.6.0"

[tool.poetry.group.dev.dependencies]
black = "^22.3.0"
pylint = "^2.15.0"
ipykernel = "^6.9.1"

[tool.poetry.group.docs.dependencies]
sphinx = "^4.5.0"
sphinx-rtd-theme = "^1.0.0"

[tool.poetry.group.test.dependencies]
pytest = "^6.2.5"

[tool.poetry.scripts]
dm_evaluate = "detectionmetrics.cli.evaluate:evaluate"
dm_batch = "detectionmetrics.cli.batch:batch"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
